# scripts/cleanup_real_flow.py
import argparse
import subprocess
from pathlib import Path


DEFAULT_NAMESPACE = "drl-scheduler"

TEMP_FILES = [
    "cluster_state.json",
    "latency-test.yaml",
    "real_node_latency_matrix.json",
    "real_node_latency_matrix.csv",
]


def run_cmd(cmd, check=False):
    print(f"\n$ {' '.join(cmd)}")

    result = subprocess.run(
        cmd,
        text=True,
        capture_output=True,
    )

    if result.stdout.strip():
        print(result.stdout.strip())

    if result.stderr.strip():
        print(result.stderr.strip())

    if check and result.returncode != 0:
        raise RuntimeError(
            f"Command failed with exit code {result.returncode}: {' '.join(cmd)}"
        )

    return result


def kubectl(*args, check=False):
    return run_cmd(["kubectl", *args], check=check)


def cleanup_service_pods(namespace: str):
    print("\n=== Delete DQN service pods only ===")

    kubectl(
        "delete",
        "pod",
        "-n",
        namespace,
        "-l",
        "app=drl-placed",
        "--ignore-not-found=true",
    )


def cleanup_latency_pods(namespace: str):
    print("\n=== Delete latency-test pods only ===")

    kubectl(
        "delete",
        "pod",
        "-n",
        namespace,
        "-l",
        "app=latency-test",
        "--ignore-not-found=true",
    )


def cleanup_files(delete_files: bool):
    if not delete_files:
        return

    print("\n=== Delete local generated files ===")

    for file_name in TEMP_FILES:
        path = Path(file_name)
        if path.exists():
            path.unlink()
            print(f"Deleted {file_name}")
        else:
            print(f"Skip {file_name}, not found")


def main():
    parser = argparse.ArgumentParser(
        description="Cleanup pods generated by real flow. Does NOT delete cluster."
    )

    parser.add_argument("--namespace", default=DEFAULT_NAMESPACE)

    parser.add_argument(
        "--services-only",
        action="store_true",
        help="Delete only app=drl-placed pods",
    )

    parser.add_argument(
        "--latency-only",
        action="store_true",
        help="Delete only app=latency-test pods",
    )

    parser.add_argument(
        "--delete-files",
        action="store_true",
        help="Delete generated local files only if explicitly requested",
    )

    args = parser.parse_args()

    if args.services_only and args.latency_only:
        raise ValueError("Use only one of --services-only or --latency-only")

    if args.services_only:
        cleanup_service_pods(args.namespace)
    elif args.latency_only:
        cleanup_latency_pods(args.namespace)
    else:
        cleanup_service_pods(args.namespace)
        cleanup_latency_pods(args.namespace)

    cleanup_files(args.delete_files)

    print("\nCleanup done. Cluster was not deleted.")


if __name__ == "__main__":
    main()